### ISSUE TITLE
Only a small part of the OCTO widgets is displayed.

### ISSUE THREAD

**Issue by LucasAR1** [steveghee/OCTO_Studio_extensions#3]
Only a small part of the OCTO widgets is displayed.
I followed the instructions and for example with the Pinger widget it worked but unfortunately not with the 360 Model Target widget. I would need this for my application.
What am I doing wrong? Vuforia Studio version 9.2.2.
Thanks in advanc
![Pinger](https://user-images.githubusercontent.com/91654696/135407648-89e25802-24cd-4718-902c-6083505b5daa.PNG)
e.

**Comment by fredBoo** [comment]
no improvement?

**Comment by steveghee** [comment]
> no improvement?

please git it a go now. pull the latest down from here and you should now see the widgets listed. 
sorry, i have put some of them behind a visibility switch. it is now removed. They should all be visible

**Comment by fredBoo** [comment]
Thanks a lot !

______________________________
Frédéric Borrel

**Comment by LucasAR1** [comment]
Only the finder and mapper have been added. Unfortunately not the 360 model target.

**Comment by steveghee** [comment]
ah, ok. sorry about that. you are right, i had hidden that one in anticipation of the product version being delivered. it is now enabled again

**Comment by LucasAR1** [comment]
Now it works. Thank you very much.
